# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: docker-dotnet6
  namespace: srikanth
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]